### PR TITLE
remove failing saucelabs platforms

### PR DESCRIPTION
**Pull request by agubler**

### CODE REVIEW

**Comment by kitsonk** [comment]
It would be better to comment them out (with an additional comment about why they were commented out), so that we can hope in vain that one day we will actually get stability from SauceLabs on these platforms or fix Intern.  It has to do with posting back the results from the unit tests and after we reach a certain size of response data, it blows up the tunnels, so it is theoretically fixable.

**Comment by agubler** [comment]
I just have an objection to commented out code in general, I certainly don't mind opening an issue for the two removed platforms. What do you think?

**Comment by kitsonk** [comment]
That is fine, though I would say that there is difference between commenting out meta data and commenting out functional code.  Also, even if there was a objection to commenting out the code, adding a comment to the code explaining what is missing and why hopefully would not be objectionable.

**Comment by kitsonk** [comment]
👍

**Pull request merged**
